linters:
  EmptyLineBetweenBlocks:
    enabled: false
  NameFormat:
    convention: 'BEM'
  SelectorFormat:
    convention: 'BEM'
  SingleLinePerSelector:
    enabled: false
  PlaceholderInExtend:
    enabled: false
