# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gil Desmarais
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Gil Desmarais is a software developer from Berlin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gil.desmarais.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gildesmarais
github_username:  gdesmarais
google_analytics: UA-59253807-1

permalink: /posts/:title_:year-:month-:day.html

disqus:
  shortname: 'gil-1'

# Build settings
markdown: kramdown
theme:
gems:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-sitemap

exclude:
  - .gitignore
  - .ruby-version
  - deploy.sh
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - yarn.lock

autoprefixer:
  only_production: true
sass:
  style: compressed

