# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gil Desmarais
subheadline: I'm a full stack developer from Berlin.

email: your-email@domain.com
description: A fullstack developer, focusing on web development, living in Berlin, working worldwide.
baseurl: ""
url: "https://gil.desmarais.de"

author: Gil Desmarais
github_username: gildesmarais
linkedin_username: gildesmarais
twitter:
  username: gldsmrs
  card: summary

# Build settings
markdown: kramdown
theme:

permalink: /posts/:title_:year-:month-:day.html

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-toc
  - jekyll-seo-tag

exclude:
  - .gitignore
  - .ruby-version
  - .nvmrc
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - vendor
  - .github/

sass:
  style: compressed
  sass_dir: assets/css/sass
