title: Gil Desmarais
lang: en
author:
  name: Gil Desmarais
github_profile_url: "https://github.com/gildesmarais"
# base64 encoded: &#99;&#111;&#110;&#116;&#97;&#99;&#116;@&#100;&#101;&#115;&#109;&#97;&#114;&#97;&#105;&#115;.&#100;&#101;
contact_email_encoded: "JiM5OTsmIzExMTsmIzExMDsmIzExNjsmIzk3OyYjOTk7JiMxMTY7QCYjMTAwOyYjMTAxOyYjMTE1OyYjMTA5OyYjOTc7JiMxMTQ7JiM5NzsmIzEwNTsmIzExNTsuJiMxMDA7JiMxMDE7"
