name: jekyll build and publish artifact with rsync

on:
  push:
    branches:
      - master
  schedule:
    - cron: "15 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Cache gems
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle config --global frozen 1
          bundle install --jobs 4 --retry 3
      - name: build the site
        env:
          JEKYLL_ENV: production
          NB_USERNAME: ${{secrets.NB_USERNAME}}
          NB_PASSWORD: ${{secrets.NB_PASSWORD}}
          NB_FOLDER: ${{secrets.NB_FOLDER}}
        run: make build
      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: "-avzr --prune-empty-dirs --delete"
          options: "--exclude *.scss"
          ssh_options: ""
          src: "_site/"
          dest: "admiral@skiff.uberspace.de:/var/www/virtual/admiral/gil.desmarais.de"

      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
      - name: Ping search engines to crawl newly generated sitemap
        run: |
          curl -fsS http://www.google.com/webmasters/sitemaps/ping?sitemap=https://gil.desmarais.de/sitemap.xml
          curl -fsS http://www.bing.com/webmaster/ping.aspx?siteMap=https://gil.desmarais.de/sitemap.xml
